//
// LoginRedefinicaoSenha.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class LoginRedefinicaoSenha: NSObject, Codable {
    public var cpf: String?
    
    public init(cpf: String?) {
        self.cpf = cpf
    }
}
