//
// RetornoSolicitacaoRedefinicaoSenha.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



@objc public class RetornoSolicitacaoRedefinicaoSenha: NSObject, Codable { 

    public var celular: String?

    public init(celular: String?) {
        self.celular = celular
    }

}
